/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function buildGraph(indexJson: string): string

export declare function calculateCentrality(graphJson: string): string

/**
 * Phase 4 entry point: end-to-end GraphRAG retrieval.
 * `options_json` must include at least `{ "query": "..." }`.
 */
export declare function dbHybridSearch(dbPath: string, optionsJson: string, embedderOptions?: string | undefined | null, destOptions?: string | undefined | null): Promise<string>

/**
 * Ingest a JSON graph (the output of `buildGraph`) into a OverGraph
 * instance at `db_path`. Returns ingest stats as JSON.
 *
 * If the caller did not supply `embedderOptions.embeddingDim`, this
 * probes the embedding endpoint once and uses the discovered dim so
 * users can swap models without recompiling or knowing the dim ahead
 * of time. The discovered dim is then validated against (or persisted
 * to) the DB sidecar manifest by `Db::open_or_create`.
 */
export declare function dbIngest(graphJson: string, dbPath: string, embedderOptions?: string | undefined | null, destOptions?: string | undefined | null): Promise<string>

/**
 * Pure vector search. Useful when the caller already has a seed and
 * just wants nearest neighbours.
 */
export declare function dbSemanticSearch(dbPath: string, query: string, k: number, whereClause?: string | undefined | null, embedderOptions?: string | undefined | null, destOptions?: string | undefined | null): Promise<string>

/**
 * DB-backed graph traversal with direction + edge-type filter.
 * `direction` accepts: "outbound" (default), "inbound", "both".
 */
export declare function dbTraverse(dbPath: string, startNodeIds: Array<string>, hops: number, edgeTypes?: Array<string> | undefined | null, direction?: string | undefined | null, destOptions?: string | undefined | null): Promise<string>

export declare function detectCycles(graphJson: string): string

export declare function filterEdgesByType(graphJson: string, edgeTypes: Array<string>): string

export declare function findShortestPath(graphJson: string, sourceId: string, targetId: string): string

/**
 * Keyword-based search over graph nodes. Matches `keyword` (case-insensitive
 * substring) against each node's `name` and `docstring`. When `node_types`
 * is provided and non-empty, only nodes whose `node_type` (lowercased) is in
 * the list are considered. An empty `keyword` returns every node that passes
 * the type filter.
 */
export declare function graphKeywordSearch(graphJson: string, keyword: string, nodeTypes?: Array<string> | undefined | null): string

/**
 * Index every supported source file under `path`. Returns a JSON-encoded
 * [`IndexResult`].
 */
export declare function index(path: string): string

/**
 * Index every supported source file under `path`, skipping files whose
 * blake3 hash matches the value stored in `<cache_path>/cache.json` from a
 * previous run. The cache file is rewritten with the latest hashes once
 * indexing is complete.
 */
export declare function indexWithCache(path: string, cachePath: string): string

export declare function kHopBfs(graphJson: string, startNodeId: string, k: number): string

/**
 * Probe the embedding endpoint. Returns `"ok"` on success, throws on
 * failure with the upstream error message.
 */
export declare function pingEmbedder(embedderOptions?: string | undefined | null): Promise<string>
